#!/bin/bash -

node_name=$1

if (! route | grep -q 10.98.1.0 )
then
    echo "$node_name: ip route add 10.98.1.0/24 via 10.100.0.1"
    ip route add 10.98.1.0/24 via 10.100.0.1
fi

if (! route | grep -q 10.98.2.0 )
then
    echo "$node_name: ip route add 10.98.2.0/24 via 10.100.0.2"
    ip route add 10.98.2.0/24 via 10.100.0.2
fi
